### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by Playwo** [xXBuilderBXx/DNetPlus-Addons#1]
Hi,
I'm here to tell you that you stole my <a href="https://github.com/Playwo/Discord.InteractivityAddon">interactivity code </a>. 
I have bad news for you as there is a license in that repository which you just lazily removed.
Please make sure that you meet the condition that is defined in the LICENSE file as I prefer not to file a DMCA takedown.

Best regards,
Playwo

**Comment by xXBuilderBXx** [comment]
Thanks for bringing up this issue, i didn't intend to steal your code or break the license i will fix that now thanks.
You can contact me on Discord if needed Builderb#0001 https://discord.gg/TjF6QDC
